foreach(required_var IN ITEMS
        THIN_TARGET_TRIPLE
        THIN_TARGET_SYSROOT
        THIN_SYSTEM_NAME
        THIN_C_COMPILER)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "${required_var} is required")
    endif()
endforeach()

list(
    APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    THIN_TARGET_TRIPLE
    THIN_TARGET_SYSROOT
    THIN_SYSTEM_NAME
    THIN_DYNAMIC_LINKER
    THIN_C_COMPILER
)

set(CMAKE_SYSTEM_NAME "${THIN_SYSTEM_NAME}")
set(CMAKE_C_COMPILER "${THIN_C_COMPILER}")
set(CMAKE_C_COMPILER_TARGET "${THIN_TARGET_TRIPLE}")
set(CMAKE_SYSROOT "${THIN_TARGET_SYSROOT}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS_INIT "-fPIC")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld -nostdlib")
if(THIN_SYSTEM_NAME STREQUAL "Windows")
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld -nostdlib")
else()
    if(NOT DEFINED THIN_DYNAMIC_LINKER OR THIN_DYNAMIC_LINKER STREQUAL "")
        message(FATAL_ERROR "THIN_DYNAMIC_LINKER is required for Linux")
    endif()
    set(
        CMAKE_EXE_LINKER_FLAGS_INIT
        "-fuse-ld=lld -nostdlib -pie -Wl,--dynamic-linker=${THIN_DYNAMIC_LINKER}"
    )
endif()

set(CMAKE_FIND_ROOT_PATH "${THIN_TARGET_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
